spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://mysqlserver/zinkworks
    username: sa
    password:
  liquibase:
    enabled: true
logging:
  level:
    org:
      springframework:
        web: TRACE
        security: TRACE