spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
  datasource:
    url: jdbc:mysql://mysqlserver:3306/atm
    username: ATM
    password: ATM
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: false
logging:
  level:
    org:
      springframework:
        web: TRACE
        security: TRACE
jwt:
  private.key: classpath:static/app.key
  public.key: classpath:static/app.pub
springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/v3/api-docs
  packagesToScan: com.daniel.sipos.atm.controller
  pathsToMatch: /**