spring:
  datasource:
    url: jdbc:mysql://mysqlserver/zinkworks
    username: sa
    password:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master-test.xml
logging:
  level:
    org:
      springframework:
        web: TRACE
        security: TRACE