version: '3'
services:
  mysqlserver:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: ZINKWORKS
      MYSQL_DATABASE: atm
      MYSQL_USER: ZINKWORKS
      MYSQL_PASSWORD: ZINKWORKS
    ports:
      - "3306:3306"
    networks:
      - common-network
    restart: always
    volumes:
      - "./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql"
  api:
    image: 'herrdani/atm:latest'
    hostname: api
    build:
      dockerfile: Dockerfile
      context: ./../../
    ports:
      - '8080:8080'
    depends_on:
      - mysqlserver
    networks:
      - common-network
    restart:
      always
  client:
    image: 'herrdani/atm-frontend:latest'
    hostname: client
    build:
      dockerfile: Dockerfile
      context: ../../vue-project/
    ports:
      - '3000:3000'
    networks:
      - common-network
networks:
  common-network:
    driver: bridge